### PR TITLE
General t3/setup frontend styling sass

### PR DESCRIPTION
**Pull request by sehersarin**
**Scrum Board Ticket:** General T2: Setup frontend styling - Sass

**Story:** General frontend setup story

**Description:** Setup sass for frontend by converting all css files to scss files for consistency amongst all components. Additionally, changed all locations in code (specifically js files ex.LoginForm.js, App.js, SignupForm.js etc.) to call the updated file name.

**Testing Criteria:** Test overall application by logging into both student and worker UI’s using credentials listed below and ensure that the frontend styling displays as expected. The actual design of the frontend is dependent on individual components - the scope of this story is primarily setting up the scss file template.

**Student Login Credentials:** username: `johndoe@gmail.com` & password: `a1234`

**Worker Login Credentials:** username: `joshuabrooks@gmail.com` & password: `j1234`

**How Reviewers can Test Code:**
1. Run the code locally and ensure no complications when starting up.
2. Navigate inside the react-ui folder and run npm start.
3. View the screens and UI to ensure it looks like design specifications/the original component before changes made.

### CODE REVIEW

**Comment by prdbondi** [comment]
Tried running, have you ever encountered this error, Seher? This could be a machine specific issue not related to the PR... 
image

**Comment by sehersarin** [comment]
Hi Peter, have you tried running the "npm install" command in the root, server and react-ui folders (I haven't received this error before but I believe it is due to uninstalled dependencies specifically from the AppointmentList.js file.)

**Comment by prdbondi** [comment]
I have, I can re run the command, perhaps when I switch branches it affects the performance

**Comment by Kyle199910** [comment]
[
Capture
](url)

Also tried running it, doesn't seem to work, and yes i tried npm install

**Comment by prdbondi** [comment]
Successful startup after re running npm install in root, and both subfolders. See errors from my terminal when attemping to log in. 
image

**Review by prdbondi — APPROVED** [review]
Ran testing steps 1-3, fixed setup errors and succesfully tested interface. Approving, having satisfied testing critera.

**Comment by sehersarin** [comment]
Great, thank you @prdbondi! Happy to hear that it worked.

**Comment by sehersarin** [comment]
@Kyle199910 I would try doing the npm install in root, and both subfolders once again. That should solve the issue (same problem that Peter was having earlier.)

**Pull request merged**
