### PR TITLE
S6 t3/implement upcoming meeting endpoint logic

### PR DESCRIPTION
**Pull request by catai9**
**Scrum Board Ticket:** S6 T3: Implement the logic for returning the upcoming meetings for a specific user.

**Story:** Story 6 Meeting/Appointment Descriptions

**Description**: Updated the logic for returning the upcoming meetings for a specific user to query the database instead of returning static/constant values.

**Testing Criteria (how I tested the code):** 
1. Running locally and testing the `/api/appointments` endpoints on port 4000 using Postman with various combinations of studentId, workerId, and status to ensure that the response was as expected. 
- studentId = 12345678 (and with/without values for status) => two objects were returned in the array object
- workerId = 8000000 (and with/without values for status) => two objects were returned in the array object
- no values specified for studentId or workerId => error thrown 
- both workerId and studentId => throw error
- workerId is string => throw error
- studentId is string => throw error

2. Running the automated server test codes and ensured that there was 100% file coverage (and passing tests) for all the unit tests. 
3. Ran the unit tests in the front end and ensured 100% file coverage (and passing tests) for the AppointmentList component. The other tests are not set up yet (in the scope of another ticket) and thus the low file coverage for the other front end files is expected.

**How Reviewers can Test Code:**
1. Run the code locally and ensure no complications when starting up (run the command `npm run-script start:dev` in the root folder OR run the command `npm start` if your node and npm versions are above 12.10.0 for node and 6.10.3 for npm).
a. Use the credentials `username: johndoe@gmail.com and password: a1234` to view the upcoming appointments. The following window should appear: 
image
b. Use the credentials `username: joshuabrooks@gmail.com and password: j1234` to view the upcoming appointments. The following window should appear:  
image
c. Open Postman and test the endpoint by sending requests to the `api/appointments` endpoint on port 4000 with various combinations of query parameters studentId, workerId and status to ensure that the response is as expected for numerical values and string values (refer to above list for examples).
**_Make sure to specify an accessToken as this is a private endpoint. An example of an accessToken is `XcCa92ZvOnQKZsGtOKOa`._**

2. Run the automated tests locally and ensure that all tests pass and have 100% file coverage. 
a. Navigate inside the `server` folder and run `npm test`. 
b. Navigate inside the `react-ui` folder and run `npm test`. All tests should pass and the AppointmentList component should have 100% file coverage (the rest are not set up yet and are in the scope for another ticket).

### CODE REVIEW

**Comment by Kyle199910** [comment]
ReactNPM test
React-Test does not state 100% coverage
ServerNPMTest
Server-Test does not state 100% coverage
Student
Worker

Both the student and worker pages do not look right for me, maybe it's my setup that causing this issue, I'm not too sure. Maybe the code will work for someone else.

**Comment by catai9** [comment]
Hi Kyle,
1. As mentioned in the description, automated testing for front end (React) will NOT have 100% file coverage as that task is still outstanding (and is out of scope for this PR).
2. The server tests should be passing... I would recommend removing or stashing any files that you have that are not related to this branch (I noticed that there are some changes in the left navigation bar). In addition, make sure to do a `git pull` and checkout this branch when running the automated tests.
3. For the student and worker pages, that repetition may be due to the data in your local database. I would recommend using pgAdmin to view the data in your appointments table. If there is a discrepancy between the data in the database and the information you see here, please let me know again and we can work it out. Otherwise, feel free to remove any undesired data entries in your local database using pgAdmin in order to get the desired layout.

Hope that helps!

**Comment by Kyle199910** [comment]
> Hi Kyle,
> 
> 1. As mentioned in the description, automated testing for front end (React) will NOT have 100% file coverage as that task is still outstanding (and is out of scope for this PR).
> 2. The server tests should be passing... I would recommend removing or stashing any files that you have that are not related to this branch (I noticed that there are some changes in the left navigation bar). In addition, make sure to do a `git pull` and checkout this branch when running the automated tests.
> 3. For the student and worker pages, that repetition may be due to the data in your local database. I would recommend using pgAdmin to view the data in your appointments table. If there is a discrepancy between the data in the database and the information you see here, please let me know again and we can work it out. Otherwise, feel free to remove any undesired data entries in your local database using pgAdmin in order to get the desired layout.
> 
> Hope that helps!

**Comment by Kyle199910** [comment]
Hi Amy, 

I have tested out the API following your instructions, results were as mentioned in the testing criteria beside returning appointments for student id and worker id.  I did the npm test again for the server, it fails from my end due to my database, it seems that my database is overpopulated with appointments. The API calls also returned many appointments for both student and worker, which matches what I see on the react app.

Capture

**Comment by catai9** [comment]
Hi Kyle,
Yes, it appears that you have deleted some needed rows from your local database and added some unnecessary rows (outside of the scripts in the `migrations` folder). To address this issue, I would recommend creating a new database in pgAdmin (shown below) and then rerunning the code in the root folder using `npm run-script start:dev`. Afterwards, try doing `npm test` again in the react-ui and server folders and it should work. 

To create a new database in pgAdmin:
1. Right click on Databases and create a new database with a new name:
image
2. Change the database name in the `.env` file and `.jest/setEnvVars.js`.
3. To avoid this problem in the future, it might be better to have one unique database for the testing and one that stores your local data. The reason it appears that multiple rows were inserted into the local database is because one of the automated unit tests attempts to insert rows. Since both the testing and local database point to the same location, the database becomes populated with test data.

Hope that helps!

**Comment by Kyle199910** [comment]
Hi Amy, 

Making a new database and changing the database pathing on the .env and .jest/setEnvVars.js files has fixed my problem, so thank you for the assistance. I redid your tests as stated in the PR description and everything looks good. This branch can now be merged.

Kyle

**Review by Kyle199910 — APPROVED** [review]
Everything looks good. Great job Amy.

**Pull request merged**
