### PR TITLE
Bugfixes/fix heroku router issues

### PR DESCRIPTION
**Pull request by catai9**
**Scrum Board Ticket**: Not related to any particular ticket, due to fixing current breaking build.

**Story**: Not related to any particular story.

**Description**: Updated the routing code due to Heroku server issues. 

**Testing Criteria:** Tested code by running locally and ensuring that it still compiled with 100% automated file coverage for the server code (and passing tests). Also deployed specific branch on Heroku and checked that the production website operated as expected.

**How Reviewers can Test Code:**
1. Run the code locally and ensure no complications when starting up (run the command `npm run-script start:dev` in the root folder OR run the command `npm start` if your node and npm versions are above 12.10.0 for node nad 6.10.3 for npm).
2. Run the automated server tests locally and ensure all tests pass and have 100% file coverage. To do this, navigate inside the `server` folder and run `npm test`. Please note that tests have not been setup for the front end so an error will occur if one attempts to run `npm test` in the root folder.
3. Navigate to production website and ensure it currently works: https://connectme-msci342.herokuapp.com/

### CODE REVIEW

**Comment by sehersarin** [comment]
Verified this PR and tested to ensure that all tests passed and had 100% coverage. 

Please note: the start command "npm run-script start:dev" was throwing errors for me. However, if I ran "npm start" instead the code worked perfectly. If you could kindly update your instructions to include this for other teammates to be aware as well. 

Other than that, I will approve and merge this PR to master.

**Comment by catai9** [comment]
Did you run `npm run-script start:dev` in the root folder or in the server folder? Make sure to run it in the root folder as per the instructions.

**Comment by sehersarin** [comment]
I ran it in the root folder.

**Comment by sehersarin** [comment]
this is the error I am receiving (image attached.) As mentioned previously, npm start command works fine.
Screen Shot 2020-10-30 at 8 18 47 PM

**Comment by catai9** [comment]
What is your node and npm versions? You may need to use `npm run start:dev` instead. `npm start` starts the app in production mode. It works but I'm curious as to why the local development version does not work on your development machine.

**Comment by sehersarin** [comment]
The "npm run start:dev" command doesn't work either. My npm version is 6.14.8 and node version is v12.19.0.

**Comment by catai9** [comment]
Oh, I see. You have an updated version of npm and node. Mine is set to v12.10.0 for node and 6.10.3 for npm. That makes sense. I will update the instructions then. Thanks Seher!

**Comment by sehersarin** [comment]
Perfect, thank you for the change. Approving and merging to master branch.

**Review by sehersarin — APPROVED** [review]

**Pull request merged**
